### PR TITLE
add structured outputs

### PR DESCRIPTION
**Pull request by ssslakter**
I've tried to implement method similar to `claudette`'s  [structured](https://github.com/AnswerDotAI/claudette/blob/main/claudette/core.py#L227), but for OpenAI API. I think it's a really nice way to get structured models right from the client.
I got it working, but I'm sure I might've missed some use cases, so I'd be happy to get your feedback on how to improve it.

Also it seems that diffs in vscode don't allow you to keep the original outputs from the notebook.  Is there another way to restore them?

### CODE REVIEW

**Comment by jph00** [comment]
Good idea! You've removed all the notebook outputs, but they're needed for the docs. So please run the notebook and save it to put the outputs back.

@ncoop57 can you take a look at this pr please?

**Comment by ncoop57** [comment]
This is fantastic @ssslakter !! Thanks for opening the PR and I'm excited to have this in 🤓 Could you please add some more examples similar to the ones shown in claudette to give people a better sense of what it is good for. Also, we are add some new ways of doing things like tool use that should hopefully simplify structured outputs and tool calling in claudette you should check it out and see what bits would be useful to swap in here. For example, we now  have better handling of creating namespaces from objects like classes: https://github.com/AnswerDotAI/claudette/pull/41

**Comment by ssslakter** [comment]
@ncoop57 This should be good now, I found a way to not touch some outputs, and added better use of tool calling

**Comment by ncoop57** [comment]
great, lgtm!! thanks @ssslakter just made a small update to how we do the namespace creation in structured. Gonna go ahead and merge this 🤓

**Pull request merged**
